#!/bin/bash

echo "**Tính tổng dãy số**"
# Tính tổng dãy số nguyên từ 1 đến n
read -p "Nhập n: " n

total=0
echo -n "S = "
for ((i=1;i<=n;i++)); do
  echo -n "$i "
  if [ $i -lt $n ]; then
    echo -n "+ "
  else
    echo -n "= "
  fi
  total=$((total + i))
done

echo "$total"

