#!/bin/bash

# Hiển thị hình tam giác
for ((i=1;i<=10;i++)); do
  for ((j=1;j<=i;j++)); do
    printf "*"
  done
  echo
done

# Hiển thị số
for i in {1..5}; do
  for j in {1..5}; do
    printf "$j "
  done
  echo
done

