#!/bin/bash

# Tạo n thư mục cho n người dùng
read -p "Nhập số người dùng: " n

for ((i=1;i<=n;i++)); do
  username="USER_$i"
  mkdir "$username" 2>/dev/null
  if [ $? == 0 ]; then
    echo "Tạo thư mục $username thành công!"
  else
    echo "Không thể tạo thư mục $username!"
  fi
done
