#!/bin/bash

echo "**Bảng cửu chương**"
# Hỏi người dùng có muốn tiếp tục
while true; do
  # Hiển thị bảng cửu chương
  read -p "Nhập số: " n

  for ((i=1;i<=10;i++)); do
    echo "$i x $n = $((i * n))"
  done
  
  while true; do
    read -p "Bạn có muốn tiếp tục (y/n)? " answer
    case $answer in
      Y)
        clear 
        break
        ;;
      y)
        clear 
        break
        ;;
      N) exit ;;
      n) exit ;;
      *) echo "Lựa chọn không hợp lệ. Vui lòng nhập y hoặc n." ;;
    esac
  done
done

