#!/bin/bash

echo "**Hệ Phương trình bậc nhất**"
# Nhập hệ số a và b từ người dùng
read -p "Nhập hệ số a: " a
read -p "Nhập hệ số b: " b

# Kiểm tra a
if [ $a -eq 0 ]; then
  if [ $b -eq 0 ]; then
    echo "Phương trình vô số nghiệm"
  else
    echo "Phương trình vô nghiệm"
  fi
else
  # Tính nghiệm
  x=$(echo "scale=2; -$b / $a" | bc)
  echo "Phương trình $a x + $b = 0, có nghiệm duy nhất là: x = $x"
fi

