#!/bin/bash

clear

# Kiểm tra xem có truyền vào 2 số nguyên hay không
if [ $# -ne 2 ]; then
  echo "Khong the thuc hien phep tinh vi vi khong truyen du 2 so nguyen."
  exit 1
fi

# Gán giá trị cho 2 biến
x=$1
y=$2

# Tính toán và hiển thị kết quả
echo "Tham so ban da truyen vao la 2 so: $x va $y"
echo "Tong: $x + $y = $((x+y))"
echo "Hieu: $x - $y = $((x-y))"
echo "Tich: $x * $y = $((x*y))"
echo "Thuong: $x / $y = $((x/y))"
echo "So du: $x % $y = $((x%y))"

